"""Updated user table

Revision ID: 9c74095d9532
Revises: 34c9f3d23046
Create Date: 2022-07-19 17:51:14.842934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c74095d9532'
down_revision = '34c9f3d23046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('access_token_expires', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('refresh_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_token_expires')
    op.drop_column('user', 'access_token_expires')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
