"""Updated user table

Revision ID: f934ab4a481c
Revises: 02c8fcf8b221
Create Date: 2022-07-21 07:13:44.252823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f934ab4a481c'
down_revision = '02c8fcf8b221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('last_request', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_request')
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
